# Generated by Django 5.2.1 on 2025-11-27 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='body',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='notice',
            old_name='date_published',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='number',
            new_name='room_number',
        ),
        migrations.AlterUniqueTogether(
            name='messmenu',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='total_rooms',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='warden',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='author',
        ),
        migrations.AddField(
            model_name='hostel',
            name='address',
            field=models.TextField(default='Unknown Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hostel',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='breakfast',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='day',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='dinner',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messmenu',
            name='lunch',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='roll',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hostel.room'),
        ),
        migrations.RemoveField(
            model_name='messmenu',
            name='snacks',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_type',
        ),
        migrations.RemoveField(
            model_name='room',
            name='vacant',
        ),
    ]
